export enum IRoles {
    SUPERADMINISTRADOR = 'SUPERADMINISTRADOR',
    ADMINISTRADOR = 'ADMINISTRADOR',
    CAJERO = 'CAJERO',
    RECAUDADOR = 'RECAUDADOR',
    TECNICO = 'TECNICO',
    CLIENTE = 'CLIENTE'
}